### ISSUE TITLE
Weird misbehaviour while parsing some responses

### ISSUE THREAD

**Issue by Lisias** [net-lisias-ksp/KSP-Forum-Preservation-Project#1]
Some URLs are inducing `pywb` to bork as follows:

```
192.168.200.107 - - [2024-07-13 09:57:01] "CONNECT forum.kerbalspaceprogram.com:443 HTTP/1.1" 200 75 2.534352
<gevent._socket3.socket [closed] at 0x7f6dd9abe500 object, fd=11, family=2, type=1, proto=0>: Invalid HTTP method: '\x17\x03\x03\x00\x13rx±\x17jap\x18ÛÁ\x14q6±ó5úäñ'
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/run/media/deck/MIRROR0/KSP/python/lib/python3.11/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
           ^^^^^^^^^^^^^^^^^^^
  File "/run/media/deck/MIRROR0/KSP/python/lib/python3.11/site-packages/gevent/pywsgi.py", line 1577, in handle
    handler.handle()
  File "/run/media/deck/MIRROR0/KSP/python/lib/python3.11/site-packages/gevent/pywsgi.py", line 471, in handle
    self.socket.sendall(response_body)
  File "/run/media/deck/MIRROR0/KSP/python/lib/python3.11/site-packages/gevent/_socketcommon.py", line 699, in sendall
    return _sendall(self, data_memory, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/deck/MIRROR0/KSP/python/lib/python3.11/site-packages/gevent/_socketcommon.py", line 409, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/deck/MIRROR0/KSP/python/lib/python3.11/site-packages/gevent/_socketcommon.py", line 338, in __send_chunk
    data_sent += socket.send(chunk, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/deck/MIRROR0/KSP/python/lib/python3.11/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2024-07-13T12:57:01Z <Greenlet at 0x7f6ddb2245e0: _handle_and_close_when_done(<bound method WSGIServer.handle of <WSGIServer at , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7f6dd9abe50)> failed with BrokenPipeError
```

The key appears to be `Invalid HTTP method: '\x17\x03\x03\x00\x13rx±\x17jap\x18ÛÁ\x14q6±ó5úäñ'`.

There're many occurences with similar, but not equal, "method" like `Invalid HTTP method: '\x17\x03\x03\x00\x138\x169Éd\x15B\r\\ Dà\x05\x87\x99\t\x0fà0'`.

**Comment by Lisias** [comment]
Interesting... `\x17\x03\x03\x00` appears to be related to the TLS protocol: https://pypi.org/project/pydivert/

**Comment by Lisias** [comment]
Yes, it's exactly like that. I think I found a bug on the `pywb` communication layer!

https://stackoverflow.com/questions/49264265/received-data-from-python-ssl-server-is-incorrect

**Comment by Lisias** [comment]
I **think** this is happening when the crawler refuses an URL...

**Comment by Lisias** [comment]
Yes, it's what is happening.

When `scrapy` decides it doesn't wants to scrap a page, it closes the current http connection. Bluntly.

But then `pywb` on the other side, besides having a http connection with the client, has a https connection with the site - and then this error is logged.

I monitored the pages before and after the error log to see if anything is missing, and until the moment, nothing was lost.

I'm removing the `bug` tag from this one, so.

**Comment by Lisias** [comment]
I will keep this open for some time, just in case.

**Comment by Lisias** [comment]
No undesired side effects, other than polluting the log. I ideally should use the proxy internally on TLS to prevent this log spam, but right now, screw it. I have more compelling things to worry about.
